In [ ]:
import numpy as np

**Basic Array Operation**

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [ ]:
np.array(a)

array([1. , 2. , 3.5])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**LINEAR SPACE**

In [ ]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**RANDOM GENERATION FUNCTIONS**

In [ ]:
np.random.rand(10)

array([0.39340313, 0.56266621, 0.94526048, 0.61138564, 0.54786732,
       0.02749918, 0.05892699, 0.15098933, 0.87473026, 0.44942119])

In NumPy, the function **numpy.random.randn()** is used to generate random numbers from a standard normal distribution.

In [ ]:
np.random.randn(10)

array([-0.39281119,  1.94673683, -0.84265408,  0.02416278, -0.65802941,
       -0.24025715,  0.11617469,  0.72173967, -0.01305225,  0.81300306])

**randint** generated numbers in a random way from given range (here it is 10-20)

In [ ]:
np.random.randint(10,20,5)

array([10, 14, 14, 17, 15])

**ARRAY ATTRIBUTE**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

**ARRAY METHODS**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

**For standard deviation**

In [ ]:
arr.std()

np.float64(2.581988897471611)

Argmax shows the index of maximum number

In [ ]:
arr.argmax()

np.int64(8)

Argmin shows the index of minimum number

In [ ]:
arr.argmin()

np.int64(0)

**RESHAPING AND RESIZING**

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])