**ARRAY INDEXING**

In [2]:
import numpy as np

**numpy indexing and slicing of vectors**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice = arr[1:5]
arr_slice

array([12, 13, 14, 15])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr[5]

np.int64(16)

**Numpy Indexing and Slicing of Matrix**

In [ ]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[3]

array([16, 17, 18, 19, 20])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[0,3]

np.int64(4)

In [ ]:
arr2 = arr[0:2,2:4]
arr2

array([[3, 4],
       [8, 9]])

**BOOLEAN INDEXING**

In [ ]:
arr = np.arange(21,31)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
even = arr%2 == 0
even

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

**ARRAY OPERATIONS**

Array operations

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [14]:
l = [10,20,30,40,50]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50, 60])

In [15]:
arr2 = np.arange(1,31).reshape(5,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [16]:
arr2 +5

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [17]:
arc = np.arange(1,21)
arc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = arc[3:8]
slice = slice * 2
slice

array([ 8, 10, 12, 14, 16])

In [24]:
arc
b = arc

In [25]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
b[3] = 30
b

array([ 1,  2,  3, 30,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**MATRIX OPERATIONS**

In [28]:
A = np.array([[1,2],[4,5]])
B = np.array([[6,7],[8,9]])

In [29]:
A

array([[1, 2],
       [4, 5]])

In [30]:
B

array([[6, 7],
       [8, 9]])

**MAATRIX MULTIPLIATION**: use @ for mat. multiplication OR use np.dot() function

In [31]:
A @ B

array([[22, 25],
       [64, 73]])

In [32]:
np.dot(A,B)

array([[22, 25],
       [64, 73]])

**TRANSPOSE OF MATRIX**

In [33]:
A

array([[1, 2],
       [4, 5]])

In [34]:
A.T

array([[1, 4],
       [2, 5]])

**ADVANCED ARRAY MANIPULATION**

Stacking Array

In [35]:
A

array([[1, 2],
       [4, 5]])

In [36]:
B

array([[6, 7],
       [8, 9]])

In [37]:
a = np.array([[1,2],[4,5]])
b = np.array([[6,7],[8,9]])

In [38]:
np.vstack((a,b))

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
np.hstack((a,b))

array([[1, 2, 6, 7],
       [4, 5, 8, 9]])

In [40]:
np.column_stack((a,b))

array([[1, 2, 6, 7],
       [4, 5, 8, 9]])

**SPLITTING ARRAYS**

In [44]:
C = np.arange(16).reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.hsplit(C,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [49]:
np.vsplit(C,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]