# **🌦️ Day 2 - NumPy: Weather Data Simulator & Analysis**
### 100 Days of Python Challenge

---

**Topics Covered Today:**
- ✅ Array Creation & Basics
- ✅ Indexing & Slicing
- ✅ Math & Aggregate Functions
- ✅ Reshaping & Broadcasting

**Project:** Simulate one year of daily weather data for 5 cities and perform real-world analysis on it!

In [1]:
import numpy as np

# **SECTION 1: Array Creation & Basics**
We'll simulate **365 days × 5 cities** of temperature data (in °C).

**Cities:** Mumbai, Delhi, Bangalore, Chennai, Kolkata

In [2]:
# Temperature data: 7 days x 3 cities (rows = days, columns = cities)
# Each row is one day, each column is one city
temperatures = np.array([
    [32, 28, 24],   # Day 1
    [33, 30, 25],   # Day 2
    [31, 35, 23],   # Day 3
    [34, 36, 26],   # Day 4
    [30, 29, 22],   # Day 5
    [29, 27, 21],   # Day 6
    [35, 31, 25],   # Day 7
])

cities = ['Mumbai', 'Delhi', 'Bangalore']
days   = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

print('Shape of array:', temperatures.shape)  # (7 rows, 3 columns)
print('Total values  :', temperatures.size)   # 7 x 3 = 21
print('Data type     :', temperatures.dtype)  # int64
print('\nFull temperature table:')
print(temperatures)

Shape of array: (7, 3)
Total values  : 21
Data type     : int64

Full temperature table:
[[32 28 24]
 [33 30 25]
 [31 35 23]
 [34 36 26]
 [30 29 22]
 [29 27 21]
 [35 31 25]]


In [3]:
# Some basic array creation functions you should know

zeros   = np.zeros((3, 3))        # 3x3 array filled with 0
ones    = np.ones((2, 4))         # 2x4 array filled with 1
day_num = np.arange(1, 8)         # [1, 2, 3, 4, 5, 6, 7]

print('zeros array:\n', zeros)
print('ones array:\n', ones)
print('day numbers:', day_num)

zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
day numbers: [1 2 3 4 5 6 7]


**PART 2: Indexing & Slicing**

In [4]:
# --- Get a single value ---
print('Day 1, Mumbai temp   :', temperatures[0, 0])   # row 0, col 0
print('Day 3, Delhi temp    :', temperatures[2, 1])   # row 2, col 1
print('Day 7, Bangalore temp:', temperatures[6, 2])   # row 6, col 2

Day 1, Mumbai temp   : 32
Day 3, Delhi temp    : 35
Day 7, Bangalore temp: 25


In [5]:
# --- Get an entire row or column ---

# All cities on Day 1 (row 0)
print('All cities on Day 1:', temperatures[0])

# All 7 days for Mumbai (column 0)
mumbai_temps = temperatures[:, 0]   # : means "all rows"
print('Mumbai all week    :', mumbai_temps)

# All 7 days for Delhi (column 1)
delhi_temps = temperatures[:, 1]
print('Delhi all week     :', delhi_temps)

All cities on Day 1: [32 28 24]
Mumbai all week    : [32 33 31 34 30 29 35]
Delhi all week     : [28 30 35 36 29 27 31]


In [6]:
# --- Slice a range of days ---

# First 3 days only
first_3_days = temperatures[0:3]
print('First 3 days:\n', first_3_days)

# Last 2 days only
last_2_days = temperatures[-2:]
print('Last 2 days:\n', last_2_days)

First 3 days:
 [[32 28 24]
 [33 30 25]
 [31 35 23]]
Last 2 days:
 [[29 27 21]
 [35 31 25]]


In [7]:
# --- Boolean Indexing (slightly tricky but very useful!) ---
# Find all temperatures above 33°C across all cities

hot_mask = temperatures > 33          # Creates a True/False array
print('Hot days mask (True = above 33°C):')
print(hot_mask)

print('\nActual hot temperatures:', temperatures[hot_mask])  # Only the True values

Hot days mask (True = above 33°C):
[[False False False]
 [False False False]
 [False  True False]
 [ True  True False]
 [False False False]
 [False False False]
 [ True False False]]

Actual hot temperatures: [35 34 36 35]


# **📊 PART 3: Math & Aggregate Functions**

NumPy makes it very easy to calculate stats — no loops needed!

In [8]:
# --- Overall stats ---
print('Highest temp this week:', np.max(temperatures))
print('Lowest temp this week :', np.min(temperatures))
print('Average temp this week:', np.mean(temperatures))

Highest temp this week: 36
Lowest temp this week : 21
Average temp this week: 28.857142857142858


In [9]:
# --- Per-city stats (axis=0 means "across all rows/days") ---
city_avg = np.mean(temperatures, axis=0)  # One avg per city
city_max = np.max(temperatures, axis=0)
city_min = np.min(temperatures, axis=0)

print('Average temp per city:', city_avg)
print('Max temp per city    :', city_max)
print('Min temp per city    :', city_min)

# Which city had the highest average?
hottest_idx = np.argmax(city_avg)         # Returns the index of the max value
print(f'\nHottest city on average: {cities[hottest_idx]} ({city_avg[hottest_idx]:.1f}°C)')

Average temp per city: [32.         30.85714286 23.71428571]
Max temp per city    : [35 36 26]
Min temp per city    : [29 27 21]

Hottest city on average: Mumbai (32.0°C)


In [10]:
# --- Per-day stats (axis=1 means "across all columns/cities") ---
day_avg = np.mean(temperatures, axis=1)   # One avg per day

print('Average temp per day:')
for i, day in enumerate(days):
    print(f'  {day}: {day_avg[i]:.1f}°C')

hottest_day_idx = np.argmax(day_avg)
print(f'\nHottest day of the week: {days[hottest_day_idx]}')

Average temp per day:
  Mon: 28.0°C
  Tue: 29.3°C
  Wed: 29.7°C
  Thu: 32.0°C
  Fri: 27.0°C
  Sat: 25.7°C
  Sun: 30.3°C

Hottest day of the week: Thu


---
## 🔀 PART 4: Reshaping & Broadcasting

### Two powerful NumPy features — let's keep it simple!

In [11]:
# --- Reshape: change the shape without changing the data ---

flat = temperatures.flatten()       # Turn 2D -> 1D (all 21 values in a line)
print('Flattened shape:', flat.shape)
print('Flattened array:', flat)

back_to_2d = flat.reshape(7, 3)    # Turn 1D -> 2D again
print('\nRestored shape:', back_to_2d.shape)

Flattened shape: (21,)
Flattened array: [32 28 24 33 30 25 31 35 23 34 36 26 30 29 22 29 27 21 35 31 25]

Restored shape: (7, 3)


In [12]:
# --- Broadcasting: apply an operation across the whole array at once ---
# Example: Convert all temperatures from Celsius to Fahrenheit
# Formula: F = C * 9/5 + 32

temps_f = temperatures * 9/5 + 32   # This applies to ALL 21 values at once!

print('Temperatures in Celsius (original):')
print(temperatures)
print('\nTemperatures in Fahrenheit:')
print(np.round(temps_f, 1))

Temperatures in Celsius (original):
[[32 28 24]
 [33 30 25]
 [31 35 23]
 [34 36 26]
 [30 29 22]
 [29 27 21]
 [35 31 25]]

Temperatures in Fahrenheit:
[[89.6 82.4 75.2]
 [91.4 86.  77. ]
 [87.8 95.  73.4]
 [93.2 96.8 78.8]
 [86.  84.2 71.6]
 [84.2 80.6 69.8]
 [95.  87.8 77. ]]


In [13]:
# --- Slightly tricky broadcasting: subtract each city's average ---
# This tells us how much each day was ABOVE or BELOW the weekly average

city_avg = temperatures.mean(axis=0)          # Shape: (3,)  — one avg per city
difference = temperatures - city_avg          # Shape: (7,3) - (3,) -> NumPy handles this!

print('City averages:', city_avg)
print('\nDifference from average (+ = hotter than usual, - = cooler):')
print(difference)
print('\nFor example, Mumbai Day 7 was', difference[6, 0], '°C above its weekly average')

City averages: [32.         30.85714286 23.71428571]

Difference from average (+ = hotter than usual, - = cooler):
[[ 0.         -2.85714286  0.28571429]
 [ 1.         -0.85714286  1.28571429]
 [-1.          4.14285714 -0.71428571]
 [ 2.          5.14285714  2.28571429]
 [-2.         -1.85714286 -1.71428571]
 [-3.         -3.85714286 -2.71428571]
 [ 3.          0.14285714  1.28571429]]

For example, Mumbai Day 7 was 3.0 °C above its weekly average


## **🏁 FINAL: Weekly Summary**

Put it all together — a simple report using everything above.

In [14]:
print('=' * 40)
print('    📋 WEEKLY WEATHER SUMMARY')
print('=' * 40)

for i, city in enumerate(cities):
    col = temperatures[:, i]          # All 7 days for this city
    print(f'\n🏙️  {city}')
    print(f'   Average : {col.mean():.1f}°C')
    print(f'   Highest : {col.max()}°C  ({days[np.argmax(col)]})')
    print(f'   Lowest  : {col.min()}°C  ({days[np.argmin(col)]})')
    print(f'   Hot days (>33°C): {np.sum(col > 33)}')

print('\n' + '=' * 40)
print('Day 2 ✅ Complete! See you on Day 3! 🚀')
print('=' * 40)

    📋 WEEKLY WEATHER SUMMARY

🏙️  Mumbai
   Average : 32.0°C
   Highest : 35°C  (Sun)
   Lowest  : 29°C  (Sat)
   Hot days (>33°C): 2

🏙️  Delhi
   Average : 30.9°C
   Highest : 36°C  (Thu)
   Lowest  : 27°C  (Sat)
   Hot days (>33°C): 2

🏙️  Bangalore
   Average : 23.7°C
   Highest : 26°C  (Thu)
   Lowest  : 21°C  (Sat)
   Hot days (>33°C): 0

Day 2 ✅ Complete! See you on Day 3! 🚀


---
## 🧠 Quick Recap

| What | How |
|---|---|
| Create array | `np.array(...)`, `np.zeros()`, `np.arange()` |
| Get one value | `arr[row, col]` |
| Get full column | `arr[:, col]` |
| Get full row | `arr[row]` |
| Filter values | `arr[arr > 33]` |
| Stats | `np.mean()`, `np.max()`, `np.min()` |
| Stats per column | `np.mean(arr, axis=0)` |
| Stats per row | `np.mean(arr, axis=1)` |
| Reshape | `arr.flatten()`, `arr.reshape(r, c)` |
| Convert all values | `arr * 9/5 + 32` (broadcasting) |